version: '3.4'

services:
  gs_shop_usermanagement.api:
    image: ${DOCKER_REGISTRY-}gsshopusermanagementapi
    build:
      context: .
      dockerfile: Api/GS_Shop_UserManagement.Api/Dockerfile
      
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Y1234"
      MYSQL_DATABASE: "Maria"
      MYSQL_USER: "Maria"
      MYSQL_PASSWORD: "Y1234"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  rabbitmq: 
    image: rabbitmq:3-management-alpine

volumes:
  mongo_data:
  mariadb_data:
